name: Test run v1

on:
  workflow_despatch
  
jobs:
  test:
    runs-on: ubuntu-1708
	steps:
	  - name: Show environment v1
	    run: env | grep ^GITHUB
	  - name: Show ref v1
	    run: echo "---> Version from $Github_REF"
