name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#触发 workflow 的事件
on: push
  workflow_despatch 
jobs:
  test:
    runs-on: ubuntu-1708
	steps:
	  - name: Show environment v1
	    run: env | grep ^GITHUB
	  - name: Show ref v1
	    run: echo "---> Version from $Github_REF"
